version: "2"

linters:
  default: all
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  disable:
    - bodyclose
    - containedctx
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - gomoddirectives
#    - gomnd
    - interfacebloat
    - ireturn
    - lll
    - mnd
    - nestif
    - noinlineerr
    - nonamedreturns
    - paralleltest
#    - stylecheck
    - revive
    - wrapcheck
    - wsl
